config/routes.rb
PosterJudging::Application.routes.draw do
    mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

    namespace :admin do
		resources :posters, :only => [:index] do
            collection { 
                post :import
                delete :clear
                get :download
                post :set_maximum
            }
        end
		resources :scores, :only => [:index, :show, :edit, :update, :destroy, :create] do
		    collection {
                 get :rankings
                 get :download_ranks
                 get :download_scores
                 
              }
        end

		resources :judges, :only => [:index, :destroy] do
			delete :clear, on: :collection
			post :create, on: :collection
		end
        root to: "admin#index"
        
		get :reset, controller: 'admin'  
		put :reset_pw, controller: 'admin'
		
		get "/register/:judge_id", to: 'admin#register', as: 'register'
		put "/register/:judge_id", to: 'admin#registerup', as: 'registerup'
	end
	
    resources :judges, :only => [:show, :update] do
        resources :scores, path: :posters, param: :poster_id, :only => [:edit, :update]{
			post :no_show
            get  :accept
            put :assign
	    }
        delete :leave
        get :register
    end

    resources :sessions, only: [:new, :create, :destroy] do
        get :download, on: :collection
        delete :signout, on: :collection
    end
    match '/signin', to: 'sessions#new', via: :get
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/signout_check', to: "application#signout_check", via: :get
    root :to => 'sessions#new'
    
    resources :posters
	

end

app/models/judge.rb
class Judge < ApplicationRecord
	has_many :scores, dependent: :destroy
	has_many :posters, through: :scores

    validates :name, :company_name, presence: true
    validates :access_code, uniqueness: true # not sure whether the number should be unique

    before_save :create_remember_token

=begin
    def self.find_available_judges
      judges = judges.where("scores_count < 3", leave: false)

      if judges.empty?
        judges = Judge.where(leave: false)
      end
      return judges
	end
=end
    private
        def create_remember_token
            self.remember_token = SecureRandom.urlsafe_base64
        end
end

app/controllers/admin/judges_controller.rb
require 'securerandom'

class Admin::JudgesController < ApplicationController
    before_action :require_login, :require_admin

    def index
        if current_user.role == "superadmin"
            @judges = Judge.all
        else
            @judges = Judge.where("role = ? or id = ?", "judge", current_user.id)
        end
    end

    def create
        admin_num = params[:admin_number].to_i
        make_user(admin_num, 'admin')
        
        num = params[:number].to_i
        make_user(num, 'judge')
        
        redirect_to admin_judges_path
    end

    def make_user(num, role)
        i = 0
        while i < num
            code = SecureRandom.hex(2)
            if(Judge.where(access_code: code).size == 0)
                judge = Judge.new('access_code' => code, 'role' => role)
                judge.save!(validate: false)
                i = i + 1
            end
        end
    end

    def clear
        Judge.where(role: "judge").destroy_all
        @judges = Judge.all
        redirect_to admin_judges_path
    end
    
    def destroy
        Judge.destroy(params[:id])
        @judges = Judge.all
        redirect_to admin_judges_path
    end
end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
    before_action :require_login, :require_correct_user
=begin
    def comeback_assign()
        no_notice = flash[:notice]? false : true
        num = 3 - @judge.scores_count
        if num >= 1
           res = assign(num)
           if res == 0 && no_notice
               flash[:notice] = nil
           end

        end
    end
    
    def set_disable()
        @disable = Array.new
	
        for score in @judge.scores
            first = Score.find(score.id).send(Score.score_terms[0])
            if  score.no_show || first >= 0
                @disable += [score.poster_id]
            end
        end
    end
=end
  def get_judge_avgs
    @judge_avgs = Hash.new
    @judge.scores.each do |score|
        if score.no_show
            @judge_avgs[score.poster_id] = "no_show"
        else
            score_sum = Score.get_score_sum().find(score.id).score_sum
            @judge_avgs[score.poster_id] = score_sum/@score_terms.size.to_f
        end
    end
  end
    #display the posters assigned to a specific judge
    def show
        @score_terms = Score.score_terms
        @judge = Judge.find(params[:id])
        @posters = @judge.posters.order(:number)
        #set_disable() #judge can edit their score later
        get_judge_avgs
        
        #orphan posters
        @orphan_poster = get_another_posters(1).first
    end  

    #update judge information (name, company name)
    def update
        @judge = Judge.find(params[:id])
        res = @judge.update_attributes(name: params[:name], company_name: params[:company])
        # this validation should be down in js
        unless res
          flash[:error] = "name & company_name cannot be blank"
          redirect_to judge_register_path(@judge) and return
        end
        sign_in @judge
        posters = assign_posters(3)
        if posters.empty?
            flash[:notice] = "There are no more posters to be assigned."
        end
        redirect_to judge_path(@judge)
    end
    
    def get_another_posters(n)
        posters = Poster.find_least_judged()
        unless posters.empty?
            posters = posters.reject {|p| @judge.posters.include?(p)}
            posters = posters.sample(n)
        end
        return posters
    end
    
    def assign_posters(n)
         #create 2 - 3 new Scores for each poster assigned to this judge
        posters = get_another_posters(n)
        posters.each do |poster|
            Score.assign_poster_to_judge(poster, @judge)
        end
        return posters
    end

    #display the form to add name and company name for a specific judge
    def register
        @judge = Judge.find(params[:judge_id])
    end
    def release_unscored_posters(judge)
        judge.scores.each do |score|
            #sum = Score.get_score_sum.find(score.id).score_sum
            first_score = score.send(Score.score_terms[0])
            next if first_score > 0
            #no show should not be deleted for later
            Score.destroy(score.id) unless score.no_show
        end
    end
     # reasign all unscored posters to other available judgers
    def leave
        @judge = Judge.find(params[:judge_id])
        begin
            #@judge.update_attributes!(:leave => true)
            release_unscored_posters(@judge)
            flash[:notice] = "You have successfully signed out!"
            sign_out
            redirect_to root_url
        rescue ActiveRecord::RecordInvalid => invalid
          flash[:error] = invalid
          redirect_to judge_path(judge_id)
        end
    end
end

app/helpers/judges_helper.rb
module  JudgesHelper

    def get_rank(role)
        case role
        when 'superadmin'
             2
        when 'admin'
             1
        when 'judge'
        	 0
        else
        	-1
        end
    end
    def higher_rank?(role)
        if  get_rank(role) >= get_rank(current_user.role)
           return true
        else
           return false
        end
    end
 
    def accept_poster_msg
        if @orphan_poster
            return "Do you want to judge poster ##{@orphan_poster.id} " + @orphan_poster.title + " ?"
        else
            return "All posters have been judged"
        end
    end

   
end

app/views/judges/judge.html.haml
!!!
%html
  %body Poster #
    %form{:name => "judge", :url=>{:controller=>"posters", :action=>"update"}}
      Novelty (research contribution of the work)
      %br/
      = succeed "1" do
        %input{:name => "cat1", :type => "radio", :value => "1"}/
      = succeed "2" do
        %input{:name => "cat1", :type => "radio", :value => "2"}/
      = succeed "3" do
        %input{:name => "cat1", :type => "radio", :value => "3"}/
      = succeed "4" do
        %input{:name => "cat1", :type => "radio", :value => "4"}/
      = succeed "5" do
        %input{:name => "cat1", :type => "radio", :value => "5"}/
      %br/
      %br/
      Utility (practical implications of the work)
      %br/
      = succeed "1" do
        %input{:name => "cat2", :type => "radio", :value => "1"}/
      = succeed "2" do
        %input{:name => "cat2", :type => "radio", :value => "2"}/
      = succeed "3" do
        %input{:name => "cat2", :type => "radio", :value => "3"}/
      = succeed "4" do
        %input{:name => "cat2", :type => "radio", :value => "4"}/
      = succeed "5" do
        %input{:name => "cat2", :type => "radio", :value => "5"}/
      %br/
      %br/
      Difficulty (the research depth and practical difficulty in getting the results - e.g. data gathering or system building)
      %br/
      = succeed "1" do
        %input{:name => "cat3", :type => "radio", :value => "1"}/
      = succeed "2" do
        %input{:name => "cat3", :type => "radio", :value => "2"}/
      = succeed "3" do
        %input{:name => "cat3", :type => "radio", :value => "3"}/
      = succeed "4" do
        %input{:name => "cat3", :type => "radio", :value => "4"}/
      = succeed "5" do
        %input{:name => "cat3", :type => "radio", :value => "5"}/
      %br/
      %br/
      Verbal Presentation
      %br/
      = succeed "1" do
        %input{:name => "cat4", :type => "radio", :value => "1"}/
      = succeed "2" do
        %input{:name => "cat4", :type => "radio", :value => "2"}/
      = succeed "3" do
        %input{:name => "cat4", :type => "radio", :value => "3"}/
      = succeed "4" do
        %input{:name => "cat4", :type => "radio", :value => "4"}/
      = succeed "5" do
        %input{:name => "cat4", :type => "radio", :value => "5"}/
      %br/
      %br/
      Written/Graphical Presentation (the poster itself)
      %br/
      = succeed "1" do
        %input{:name => "cat5", :type => "radio", :value => "1"}/
      = succeed "2" do
        %input{:name => "cat5", :type => "radio", :value => "2"}/
      = succeed "3" do
        %input{:name => "cat5", :type => "radio", :value => "3"}/
      = succeed "4" do
        %input{:name => "cat5", :type => "radio", :value => "4"}/
      = succeed "5" do
        %input{:name => "cat5", :type => "radio", :value => "5"}/
%br/
%br/
%br/
%button{:type => "submit"} Submit

app/views/judges/show.html.haml
-# in app/views/judges/show.html.haml
:javascript
  $(document).on("click", '#accept_button', function(e){
    if(confirm("#{accept_poster_msg()}")){
    } else {
      e.preventDefault();
      window.location.reload();
    }
  });
%h3 <strong> Howdy</strong>, #{@judge.name} from #{@judge.company_name}!
%br

%h4 Assignments
- if @posters.empty?
  %p None
- else
  %table{class: "table table-bordered", id: "assigned_posters_table"}
    %thead
      %tr
        %th Poster #
        %th Title
        %th Average
        %th Grade
    - @posters.each do |poster|
      %tbody
        %tr
          %td= poster.number
          %td= poster.title
          %td= show_score(@judge_avgs[poster.id])
          %td= button_to 'Grade', edit_judge_score_path(@judge.id, poster.id), :method => :get

- if @orphan_poster
  = button_to 'Accept Another Poster', judge_score_assign_path(@judge.id, @orphan_poster.id),  method: :put, class: "btn btn-lg btn-default btn-block", id: "accept_button"