config/routes.rb
PosterJudging::Application.routes.draw do
    mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

    namespace :admin do
		resources :posters, :only => [:index] do
            collection { 
                post :import
                delete :clear
                get :download
                post :set_maximum
            }
        end
		resources :scores, :only => [:index, :show, :edit, :update, :destroy, :create] do
		    collection {
                 get :rankings
                 get :download_ranks
                 get :download_scores
                 
              }
        end

		resources :judges, :only => [:index, :destroy] do
			delete :clear, on: :collection
			post :create, on: :collection
		end
        root to: "admin#index"
        
		get :reset, controller: 'admin'  
		put :reset_pw, controller: 'admin'
		
		get "/register/:judge_id", to: 'admin#register', as: 'register'
		put "/register/:judge_id", to: 'admin#registerup', as: 'registerup'
	end
	
    resources :judges, :only => [:show, :update] do
        resources :scores, path: :posters, param: :poster_id, :only => [:edit, :update]{
			post :no_show
            get  :accept
            put :assign
	    }
        delete :leave
        get :register
    end

    resources :sessions, only: [:new, :create, :destroy] do
        get :download, on: :collection
        delete :signout, on: :collection
    end
    match '/signin', to: 'sessions#new', via: :get
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/signout_check', to: "application#signout_check", via: :get
    root :to => 'sessions#new'
    
    resources :posters
	

end

app/views/admin/index.html.haml
%br
= button_to "View Posters", admin_posters_path, method: "get", class: "btn btn-lg btn-default btn-block"
%br
= button_to "View Users", admin_judges_path, method: "get", class: "btn btn-default btn-lg btn-block"
%br
= button_to "View Scores", admin_scores_path, method: "get", class: "btn btn-default btn-lg btn-block"
%br
= button_to "View Poster Rankings", rankings_admin_scores_path, method: "get", class: "btn btn-default btn-lg btn-block"
%br
= button_to "Reset Password", admin_reset_path, method: "get", class: "btn btn-default btn-lg btn-block"
%br

= "Event Date:   "
= @event_date_set.inspect

%br 
%br
= form_tag admin_root_path, :id=> "form_id", :method => :get do 
  = date_field("event", "date",:default => Date.today) 
  %br
  = submit_tag 'Update Date'
  
= "Max number of posters:   "
= @max


= form_tag admin_root_path,  :method => :get do
  = text_field_tag :poster_number, nil, placeholder: "Max number of Posters"
  = submit_tag 'Update'


=button_to "Student Signup Page", new_poster_path, method: "get"


= "IAP QR Code:"

.qrcode
  = image_tag "qrcode.png"
.pull-center
  = button_to 'download QR code', download_sessions_path, method: "get"
  

app/views/admin/reset.html.haml
= button_to "Back", admin_root_path, method: "get", class: "btn btn-default"

= form_tag admin_reset_pw_path, method: "put", multipart: true do
    .form-group
        = label_tag :new_pw, "Enter new password: "
        = password_field_tag :new_pw, "", class: "form-control"

    .form-group
        = label_tag :confirm_pw, "Confirm new password: "
        = password_field_tag :confirm_pw, "", class: "form-control"

    .form-group
        = submit_tag "Submit", class: "btn btn-default"