config/routes.rb
PosterJudging::Application.routes.draw do
    mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

    namespace :admin do
		resources :posters, :only => [:index] do
            collection { 
                post :import
                delete :clear
                get :download
                post :set_maximum
            }
        end
		resources :scores, :only => [:index, :show, :edit, :update, :destroy, :create] do
		    collection {
                 get :rankings
                 get :download_ranks
                 get :download_scores
                 
              }
        end

		resources :judges, :only => [:index, :destroy] do
			delete :clear, on: :collection
			post :create, on: :collection
		end
        root to: "admin#index"
        
		get :reset, controller: 'admin'  
		put :reset_pw, controller: 'admin'
		
		get "/register/:judge_id", to: 'admin#register', as: 'register'
		put "/register/:judge_id", to: 'admin#registerup', as: 'registerup'
	end
	
    resources :judges, :only => [:show, :update] do
        resources :scores, path: :posters, param: :poster_id, :only => [:edit, :update]{
			post :no_show
            get  :accept
            put :assign
	    }
        delete :leave
        get :register
    end

    resources :sessions, only: [:new, :create, :destroy] do
        get :download, on: :collection
        delete :signout, on: :collection
    end
    match '/signin', to: 'sessions#new', via: :get
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/signout_check', to: "application#signout_check", via: :get
    root :to => 'sessions#new'
    
    resources :posters
	

end

app/models/score.rb
class Score < ApplicationRecord
	#attr_accessor :novelty, :utility, :difficulty, :verbal, :written, :no_show
	belongs_to :judge, counter_cache: true
	belongs_to :poster, counter_cache: true
	validates :novelty, :utility, :difficulty, :verbal, :written, numericality: true
	validates :novelty, :utility, :difficulty, :verbal, :written, numericality: { other_than: 0 }

	#attr_accessor :judge_id, :poster_id
	
	
	
    def self.score_terms
       %w(novelty utility difficulty verbal written)
    end
    
    def self.assign_poster_to_judge(poster, judge)
        score = Score.find_by(poster_id: poster.id, judge_id: judge.id)
        unless score
            score = judge.scores.build(novelty: -1, utility: -1, difficulty: -1, verbal: -1, written: -1, no_show: false)
            poster.scores << score
            score.save!
        end
    end

    def self.get_score_sum
        str = "("
        score_terms.each do |term|
             str += term + "+"
        end
        str = str.gsub(/\+\z/, ") ") + "as score_sum"
        return Score.select(str)
    end

end

app/controllers/admin/scores_controller.rb
# in /app/controllers/admin/scores_controller.rb
require 'csv'

class Admin::ScoresController < ApplicationController
  before_filter :require_login, :require_admin
  def is_i?(str)
    !str.match(/^[-+]?[0-9]+$/).nil?
  end
  
  def avgs_init
    @judge_avgs = Hash.new
    @poster_avg = 0
    @term_avgs = Hash.new()
    @score_terms.each do |term|
      @term_avgs[term] = 0
    end
  end
  
  def avgs_final(count)
    if count > 0
        @poster_avg /= count.to_f
        @term_avgs = @term_avgs.map {|k,v| k,v = k,v/count.to_f}.to_h
    else
        @term_avgs = @term_avgs.map {|k,v| k,v = k, -1}.to_h
        @poster_avg = -1
    end
  end
  
  def cal_poster_avg
    avgs_init
    count = 0
    @scores.each do |score|
      score_sum = Score.get_score_sum().find(score.id).score_sum
      if score_sum > 0
        @judge_avgs[score.judge_id] = score_sum/@score_terms.size.to_f
        @poster_avg += @judge_avgs[score.judge_id]
        count += 1
        @score_terms.each do |term|
          @term_avgs[term] += score[term]
        end
      end
    end
    
    avgs_final(count)
    return count
  end

  def get_poster_avg(poster)
    @scores = poster.scores.sort_by {|score| score.judge.name}
    @poster_avg = -1
    count = 0
    if poster.scores_count > 0
      count = cal_poster_avg
    end
    return {:avg => @poster_avg, :count => count}
  end
  def get_posters_by_keywords(keywords)
      keywords =  keywords || ""
      keywords = keywords.gsub(/[^a-z0-9\s]/i, " ")
      posters = []
      if keywords.empty? || keywords.match(/^\s+$/)
        posters = Poster.all.order(:number)
      elsif is_i?(keywords)
        posters = Poster.where(number: keywords.to_i)
      else
        posters = Poster.find_by_keywords(keywords).order(:number)
      end
      
      return posters
  end

  def select_posters_by_filter(origin_posters, posters, filter)
    origin_posters.each do |poster|
      #assume the poster is unscored at first, then we will find out whether it is scored or not
      # a poster in origin_posters is either completed or inprogress
      no_show = false
      count = 0
      poster.scores.each do |score|
        if score.no_show
          unless no_show
            posters << poster if filter == "no_show"
            no_show = true
          end
        elsif score.send(Score.score_terms[0]) > 0
            count += 1
        end
      end
      
      if count >= 3
        posters << poster if filter == "completed"
      else
        posters << poster if filter == "inprogress"
      end
    end
    return posters
  end

	def select_posters(origin_posters, filter)
	  inprogress_posters = origin_posters.select {|p| p.scores_count > 2 }
	  undone_posters = origin_posters - inprogress_posters
	  
	  if filter == "undone"
	    return undone_posters
	  end
	  
	  posters = []
	  
	  if filter == "no_show"
	    undone_posters.each do |poster|
        poster.scores.each do |score|
          posters << poster if score.no_show
          break
        end
      end
	  end
	  #among assigned posters, there are three type: inprogress, no_show, completed
	  # we now label each poster with its write type
    select_posters_by_filter(inprogress_posters, posters, filter)
    return posters
	end

def filter_posters(status)
    if status
        session[:status] = status
    end
    if session[:status] && session[:status] != "all"
      @posters = select_posters(@posters, session[:status])
    end
    @filter = session[:status] || ""
end

  def index
    @score_terms = Score.score_terms
    @posters = get_posters_by_keywords(params[:searchquery])
    @poster_avgs = Hash.new
    filter_posters( params[:status])
    # calcualte average score for each poster
    @posters.each do |poster|
		   @poster_avgs[poster.id] = get_poster_avg(poster)
    end
    if request.xhr?
      render :partial => 'index_partial'
    end
    
  end
  
  def show
    @score_terms = Score.score_terms
    poster_id = params[:id]
    @poster = Poster.find(poster_id)
    get_poster_avg(@poster)
  end

  def edit
    score   = Score.find(params[:id])
    @poster = score.poster
    @judge  = score.judge
    render 'scores/edit'
  end
  
  def create
    poster_id = params[:poster_id]
    @poster = Poster.find(poster_id)
    @judge = Judge.find_by(access_code: params[:judge_code])
    if @judge
      score = Score.find_by(judge_id: @judge.id, poster_id: poster_id)
      if score
        flash[:notice]  = "Judge "+ @judge.name + " is already in the score table"
      else
        Score.assign_poster_to_judge(@poster, @judge)
      end
    else
      flash[:notice]  = "Cannot find Judge with access code " + params[:judge_code]
    end
    redirect_to admin_score_path(@poster)
  end
  
  def destroy
    score = Score.find(params[:id])
    poster = score.poster
    score.destroy
    @scores = poster.scores
    @score_terms = Score.score_terms
    redirect_to admin_score_path(poster)
  end

  def download_ranks
    
        send_file("downloads/rankings.csv", :filename => "rankings.csv")
  end
  
  def download_scores
        File.delete("downloads/scores.csv") if File.exists?("downloads/scores.csv")
        @scores = Score.includes(:poster, :judge).order("posters.number")

        CSV.open("downloads/scores.csv", "wb") do |csv|
            csv << [:id, :poster_number, :judge_name] + Score.score_terms + [:no_show, :poster_title, :poster_presenter, :judge_company_name] 
            for score in @scores
              poster = Poster.find(score.poster_id)
              judge = Judge.find(score.judge_id)
              if poster and judge #need to exclude scores from prior competitions since we never delete those...
              	csv << [score.id, poster.number, judge.name] + Score.score_terms.map{ |v| score.send(v) } + [score.no_show, poster.title, poster.presenter, judge.company_name]
              end
            end
        end
        send_file("downloads/scores.csv")
  end

  def rankings
        @score_terms = Score.score_terms
        @posters = Poster.all
        @poster_avgs = Hash.new
        @posters.each do |poster|
          state = get_poster_avg(poster)
          poster_avg = state[:avg]
          if poster_avg < 0
            @posters = @posters.reject {|p| p.id == poster.id}
          else
            @poster_avgs[poster.id] = state
          end
        end
        
        @posters = @posters.sort_by{|poster| @poster_avgs[poster.id][:avg]}.reverse
       
        
        create_rank_file(@posters, @poster_avgs)  #FIXME this should be run before a download, right?
  end
  
  def create_rank_file(posters, scores)
        File.delete("downloads/rankings.csv") if File.exists?("downloads/rankings.csv")
        CSV.open("downloads/rankings.csv", "wb") do |csv|
            csv << ["rank", "presenter", "title", "#scores", "avg.score"]
            rank = 0
            temp_score = 0.0
            for poster in posters
                # lists equal rank for equal scores by incrementing with change in scores
                if temp_score != scores[poster.id][:avg]
                  temp_score = scores[poster.id][:avg]
                  rank += 1
                end
                csv << [rank, poster.presenter, poster.title, scores[poster.id][:count], scores[poster.id][:avg]]
            end
        end
  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    before_action :require_login
    #render the view for judging each poster
    def decide_score_exist
        score_exist = false
        @poster.scores.each do |score|
            score_exist = true if score.send(Score.score_terms[0]) > 0
        end
        return score_exist
    end
    def edit
        @poster = Poster.find(params[:poster_id])
        @judge = Judge.find(params[:judge_id])
        if !@judge.posters.include?(@poster)
            flash[:notice] = "#{@poster.title} was not assigned to #{@judge.name}."
            redirect_to judge_path(@judge)
        end
        @score_exist = decide_score_exist
    end
    
    #update the Score associated with a specific poster and a specific judge
    def update
        #check to make sure all radio buttons are checked
        
        judge_id  = params[:judge_id]
        poster_id = params[:poster_id]
        @score = Score.where(judge_id: judge_id, poster_id: poster_id).first()
        score = params[:score]
        score = score.map {|k,v| k, v = k.to_sym, v.to_i}.to_h
        
        if @score.no_show
            score[:no_show] = false
        end
        begin
            @score.update_attributes!(score)
            flash[:notice] = "Score is submitted successfully"
            if admin?
              redirect_to admin_score_path(poster_id) and return
            else
              redirect_to judge_path(judge_id) and return
            end
        rescue ActiveRecord::RecordInvalid => invalid
           flash[:notice] = invalid
           redirect_to edit_judge_score_path(judge_id, poster_id)
        end
    end

    

    def no_show
        poster_id = params[:score_poster_id]
        judge_id = params[:judge_id]
        score = Score.find_by(judge_id: judge_id, poster_id: poster_id)
        score.update_attributes!(novelty: -1, utility: -1, difficulty: -1, verbal: -1, written: -1, no_show: true)
        if admin?
            redirect_to admin_score_path(poster_id)
        else
            redirect_to judge_path(judge_id)
        end
    end
        #create 2 - 3 new Scores for each poster assigned to this judge
    def assign
        judge ||= Judge.find(params[:judge_id])
        poster = Poster.find(params[:score_poster_id])
        if  poster
            Score.assign_poster_to_judge(poster, judge)
            flash[:notice] = "You have successfully added poster #" + poster.number.to_s
        end
        redirect_to judge_path(params[:judge_id])
    end
    
end

app/helpers/scores_helper.rb
module  ScoresHelper
    def show_score(score)
        t = score.to_s.match(/^(\d+(\.\d+)?)$/)
        if  t
        	(score.class ==  Float) ? ("%.3f" % score) : score
        elsif score == "no_show"
            "No Show"
        else
        	'-'
        end
    end
    
    def show_avg(no_show, avg)
        if no_show
           "No Show" 
        else
            show_score(avg)
        end
    end
    
    def show_poster_avg(poster, avg)
        if poster.scores.empty?
            no_show = false
        else
            no_show = true
            poster.scores.each do |score|
                no_show = false unless score.no_show
            end
        end
        show_avg(no_show, avg)
    end
    

    def filter(state)
       return @filter.eql?(state)
    end

    def no_show_msg
        msg = "Are you sure?"
        if (@score_exist && !admin?)
            msg = "This poster is scored by other judges, are you sure?"
        end
        return msg
    end
    
=begin    
  # method separated from /app/views/admin/scores/index.html.haml
  
  # used to count # of times a poster is scored = # of scoring judges
  def get_actual_scores_count(poster)
      return (poster.scores_count - poster.scores.where("#{Score.score_terms[0]} = -1").count)
  end
=end  
  def view_ranking(viewed_poster_avg, i)
      @temp_poster_avg ||= 0.0
      if viewed_poster_avg != @temp_poster_avg
          @temp_poster_avg = viewed_poster_avg
          return i + 1
      else
          return i
      end
  end
end

app/views/admin/scores/_index_partial.html.haml
- @posters.each do |poster|
        %tr
                %td= poster.number
                %td= poster.presenter
                %td= poster.title
                %td= show_poster_avg(poster, @poster_avgs[poster.id][:avg])
                -# counts total number of actually scored posters = judges
                %td= @poster_avgs[poster.id][:count]
                %td= link_to "See Details", admin_score_path(poster)

app/views/admin/scores/index.html.haml
-# in app/views/admin/scores/index.html.haml
%body

-#        $(document).on("change", 'input[type="checkbox"]', function(){
-#                document.getElementById("status_form").submit();
-#        });
:javascript
        var FilterTable = {
                setup: function() {
                        $(document).on("change", 'input[type="radio"]', FilterTable.filter);
                        $('#search_form').on('submit', FilterTable.filter);
                }
                ,filter: function(e){
                        e.preventDefault();
                        if (e.type == "change"){
                                $('#searchquery').val('');        
                        };
                        
                        $.ajax({
                                type: 'GET',
                                url: '/admin/scores',
                                data: {
                                        status: $('input[name="status"]:checked').val(),
                                        searchquery: $('#searchquery').val()
                                },
                                success:  function(data){
                                        $('#scores_content').html(data);
                                        if (e.type == "submit") {
                                                $('input[type="submit"]').prop('disabled', false);
                                        };
                                },
                                error: function (error) {
                                        alert(error);
                                }
                        });
                }
        };
        $(FilterTable.setup);
= button_to "Back", admin_root_path, method: "get", class: "btn btn-default btn"

= button_to "Download", download_scores_admin_scores_path, method: "get", class: "btn btn-default btn"
  
-#= form_tag admin_scores_path, :id => "status_form", :class => "pull-left", :method => :get do
-#        = label_tag 'No Show'
-#        = check_box_tag "status[no_show]", id: "status_no_show"
-#        = label_tag 'Partially Scored'
-#        = check_box_tag "status[unscored]", id: "status_unscored"
-#        = label_tag 'Completely Scored'
-#        = check_box_tag "status[scored]", id: "status_scored"

= form_tag admin_scores_path, :id => "status_form", :class => "pull-left", :method => :get do
        = label_tag 'All'
        = radio_button_tag "status","all",  filter("all"),id: "status_all"
        = label_tag "No Show", nil, class: "padding-label"
        = radio_button_tag "status", "no_show", filter("no_show"), id: "status_no_show"
        = label_tag 'Need More Judges', nil, class: "padding-label"
        = radio_button_tag "status","undone", filter("undone"), id: "status_undone"
        = label_tag 'In Progress', nil, class: "padding-label"
        = radio_button_tag "status","inprogress", filter("inprogress"), id: "status_inprogress"
        = label_tag 'Completed', nil, class: "padding-label"
        = radio_button_tag "status","completed",  filter("completed"),id: "status_completed"
        
= form_tag admin_scores_path, :id => "search_form", :class => "navbar-search pull-right", :method => :get do
        = text_field_tag 'searchquery', nil, :class => "search-query span3", :placeholder => "Search"
        = submit_tag "Search", class: "btn btn-success btn-md"
      
%table{class: "table table-bordered", id: "scores_table"}
        %thead
                %th Poster #
                %th Presenter
                %th Title
                %th Average
                %th # Scores
                %th Detail
        %tbody{id: "scores_content"}
                - @posters.each do |poster|
                        %tr
                                %td= poster.number
                                %td= poster.presenter
                                %td= poster.title
                                %td= show_poster_avg(poster, @poster_avgs[poster.id][:avg])
                                -# counts total number of actually scored posters = judges
                                %td= @poster_avgs[poster.id][:count]
                                %td= link_to "See Details", admin_score_path(poster)

app/views/admin/scores/rankings.html.haml
:javascript
    setInterval(function() {window.location.reload();}, 5000);

= button_to "Back", admin_root_path, method: "get", class: "btn btn-default"

= button_to 'Download', download_ranks_admin_scores_path, method: "get", class: "btn btn-default"

%table{class: "table table-bordered", id: "ranking_table"}
    %thead
        %th Rank
        %th Presenter
        %th Title
        %th #Scores
        %th Avg. Score
    %tbody
        - i = 0
        - @posters.each do |poster|
            %tr
                - viewed_poster_avg = show_poster_avg(poster, @poster_avgs[poster.id][:avg])
                %td= i = view_ranking(viewed_poster_avg, i)
                %td= poster.presenter
                %td= poster.title
                %td= @poster_avgs[poster.id][:count]
                %td= viewed_poster_avg

app/views/admin/scores/show.html.haml
-# in app/views/admin/scores/show.html.haml
= button_to "Back", admin_scores_path, method: "get", class: "btn btn-default btn"
%h2 Details about Poster ##{@poster.number}

%ul#details
title: #{@poster.title}
%table{class: "table table-bordered", id: "details_table"}
  %thead
    %tr
      %th Judge
      - @score_terms.each do |term|
        %th= term
      %th Average
      %th Edit
      %th Delete
  %tbody
    -@scores.each do |score|
      %tr
        %td= score.judge.name
        - @score_terms.each do |term|
          %td= show_score(score.send(term))
        %td= show_avg(score.no_show, @judge_avgs[score.judge_id])
        %td= link_to 'Edit', edit_admin_score_path(score), method: :get
        %td= link_to 'Delete', admin_score_path(score), method: :delete
    - unless @scores.empty?
      %tr
        %td Average
        - @score_terms.each do |term|
          %td= show_score(@term_avgs[term])
        %td= show_score(@poster_avg)
        %td
        %td

= form_tag admin_scores_path, method: :post  do
  = label_tag "Enter Judge Access Code:" 
  = text_field_tag 'judge_code', "", size: 20
  = hidden_field_tag "poster_id", @poster.id
  = submit_tag 'Create New Score', class: "btn btn-default btn"