config/routes.rb
PosterJudging::Application.routes.draw do
    mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

    namespace :admin do
		resources :posters, :only => [:index] do
            collection { 
                post :import
                delete :clear
                get :download
                post :set_maximum
            }
        end
		resources :scores, :only => [:index, :show, :edit, :update, :destroy, :create] do
		    collection {
                 get :rankings
                 get :download_ranks
                 get :download_scores
                 
              }
        end

		resources :judges, :only => [:index, :destroy] do
			delete :clear, on: :collection
			post :create, on: :collection
		end
        root to: "admin#index"
        
		get :reset, controller: 'admin'  
		put :reset_pw, controller: 'admin'
		
		get "/register/:judge_id", to: 'admin#register', as: 'register'
		put "/register/:judge_id", to: 'admin#registerup', as: 'registerup'
	end
	
    resources :judges, :only => [:show, :update] do
        resources :scores, path: :posters, param: :poster_id, :only => [:edit, :update]{
			post :no_show
            get  :accept
            put :assign
	    }
        delete :leave
        get :register
    end

    resources :sessions, only: [:new, :create, :destroy] do
        get :download, on: :collection
        delete :signout, on: :collection
    end
    match '/signin', to: 'sessions#new', via: :get
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/signout_check', to: "application#signout_check", via: :get
    root :to => 'sessions#new'
    
    resources :posters
	

end

app/views/layouts/application.html.haml
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'PosterJudging'
    %meta{name: "viewport", content: "width= device-width, initial-scale=1"}
    = stylesheet_link_tag    :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    :javascript
      var  ConfirmPopup = {
        setup: function() {
          $(document).on('click', '#signout', ConfirmPopup.getConfirmInfo);
        }
        ,getConfirmInfo: function(event) {
          event.preventDefault();
          $.ajax({
            type: 'GET',
            url: $(this).attr('href'),
            datatype: "json",
            success: ConfirmPopup.showConfirmInfo,
            error: function (error) {
              $("#signout_button").trigger("click");
              return false;
            }
          });
        }
        ,showConfirmInfo: function(json){
          data = $.parseJSON(json);
          if (data){
            $("#signout_button").trigger("click");
          } else{
            $("#confirm_button").trigger("click");
          };
          return false;
        }
      };
      $(ConfirmPopup.setup);
    %div{class: "header"}
      - if current_user
        = link_to "Sign out", signout_check_path, :method => :get,  class: "sign-out", id: "signout", :remote => true
        = button_to "sign out", signout_path, :method => :delete,  class: "invisible",id: "signout_button"
        = button_to "confirm", signout_sessions_path, :method => :delete,  class: "invisible",id: "confirm_button"
      =image_tag('logo.png', style: "position: absolute; top: 35px;")


    %div{:class => "content container", id: "page-content"}
      %br
      %div{:class => "col-sm-12 col-lg-12"}
        - if flash[:notice]
          %div{class: "alert alert-success"}
            #notice.message= flash[:notice]
        - elsif flash[:alert]
          %div{class: "alert alert-danger"}
            #notice.message= flash[:alert]
        - elsif flash[:error]
          %div{class: "alert alert-danger"}
            #notice.message= flash[:error]
      = yield
      

  